---
sidebar: sidebar
permalink: task-audit-data-sense-actions.html
keywords: compliance, actions, view progress
summary: Data Sense logs management activities that are performed on files from all the working environments and data sources that Data Sense is scanning. You can view the contents of the Data Sense audit log files, or download them, to see what file changes have occurred, and when.
---

= Auditing the history of Data Sense actions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Data Sense logs management activities that are performed on files from all the working environments and data sources that Data Sense is scanning. You can view the contents of the Data Sense audit log files, or download them, to see what file changes have occurred, and when.

For example, you can see what request was issued, the time of the request, and details such as source in case a file was deleted, or source and destination in case a file was moved.

The audit log is located on the Data Sense instance/virtual machine in: `/opt/netapp/audit_logs/<date>/DataSense_audit_log_<date>_<process_name>.log`

Each line in the audit log will contain information in this format:

`2022-05-25T11:25:14,297 | INFO | audit_logger | <module> | 0 | 0 | None | File <full file path> deleted from device <device path>`

The following information is included for each event in the log:

* Date and time – full timestamp for the event

* Action type (delete, copy, move, create policy, update policy, download JSON report, etc.)

* File name (if the action is relevant to a file)

* Details for the action – what was done: depends on the action

** Policy name
** For move - Source and destination
** For regular copy - Source and destination
** For tag – tag name
** For assign to – user name
** For email alert – email address / account
